version: "3.4"
services:
  ott-cm-v5:
    build: .
    restart: on-failure
    networks:
      - cm-v5-network
    ports:
      - 1993:1993
    depends_on:
      - "redis-cluster"
    command: ["./main"]
  redis-cluster:
    image: grokzen/redis-cluster
    restart: on-failure
    networks:
      - cm-v5-network
    ports:
      - "7000-7050:7000-7050"
      - "5000-5010:5000-5010"
    healthcheck:
      test: ["CMD", "redis-cli", "-c", "-h", "127.0.0.1", "-p", "7000"]
      interval: 30s
      timeout: 10s
      retries: 5
networks:
  cm-v5-network:
    driver: bridge
