DOCKER_IMAGE_NAME: a
CI_ENVIRONMENT_NAME: a
IMAGE_TAG: a
POD_LIMIT_CPU: a
POD_LIMIT_MEM: a
POD_REQUEST_CPU: a
POD_REQUEST_MEM: a
VAULT_HOST: a
VAULT_PORT: a
VAULT_ROLE_ID: a
VAULT_SECRET_ID: a
CONTAINER_PORT: a
SERVICE_DOMAIN: a