package schema

import "database/sql"

type EntityVodStruct struct {
	Id                  string
	Group_id            string
	Parent_id           sql.NullString
	Type                string
	Title               string
	Known_as            string
	Short_description   string
	Long_description    string
	Episode             int
	Season              int
	Episode_name        string
	Season_name         string
	Resolution          int
	Runtim              int
	Share_urls          string
	Slug                string
	Slug_seo            string
	Released            int
	Link_play           string
	Source_id           string
	Caption             sql.NullString
	Caption_langs       sql.NullString
	Release_year        string
	Publish_date        string
	Release_date        string
	Isdvr               int
	Odr                 int
	Created_at          string
	Created_by          int
	Updated_at          string
	Status              int
	Schedule_date       string
	Dvr_link_play       string
	Geo_check           int
	Category            int
	Total_seasons       int
	Vod_schedule        string
	Expire_date         sql.NullString
	Key_map             string
	Views               int32
	Avg_rate            float64
	Trailer_id          string
	Total_rate          int
	Current_episode     string
	Age_range           string
	Enable_ads          int
	New_update_date     sql.NullString
	Catchup_day         int
	Admin_note          sql.NullString
	Player_logo_id      sql.NullString
	Content_provider_id sql.NullString
	Custom_ads          sql.NullString
	Intro_start         sql.NullInt64
	Intro_end           sql.NullInt64
	Outtro_start        sql.NullInt64
	Outtro_end          sql.NullInt64
	Version_migrate     string
}
