apiVersion: v1
kind: Service
metadata:
  name: {{.Values.DOCKER_IMAGE_NAME}}
  namespace: ott-{{.Values.CI_ENVIRONMENT_NAME}}-h
spec:
  ports:
  - port: {{.Values.CONTAINER_PORT}}
    protocol: TCP
  selector:
    run: {{.Values.DOCKER_IMAGE_NAME}}
