apiVersion: v1
kind: Service
metadata:
  name: ${DOCKER_IMAGE_NAME}
  namespace: ott-${CI_ENVIRONMENT_NAME}
spec:
  ports:
  - port: ${CONTAINER_PORT}
    protocol: TCP
  selector:
    run: ${DOCKER_IMAGE_NAME}
