basePath: /backend/cm/v4
host: localhost:1993
info:
  contact:
    email: thu.nguyen.thuy@dzones.vn
    name: API Support
    url: http://www.swagger.io/support
  description: ott-backend-v3 server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger API Version 4
  version: "4.0"
paths:
  /home_ribbons_v3:
    get:
      consumes:
      - application/json
      description: GetHomeRibbonsV3
      produces:
      - application/json
      responses:
        "200":
          description: answer
          schema:
            type: string
        "400":
          description: ok
          schema:
            type: string
        "404":
          description: ok
          schema:
            type: string
        "500":
          description: ok
          schema:
            type: string
      summary: GetHomeRibbonsV3
      tags:
      - ribbons_v3
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
  BasicAuth:
    type: basic
swagger: "2.0"
